In [1]:
import pandas as pd
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN, MeanShift
from sklearn.preprocessing import MinMaxScaler

In [50]:
dados

,jogadores,jogo,min_em_quadra,pontos,cesta_de_3_pts,cesta_de_2_pts,lances_livres,rebotes,rebotes_ofensivos,rebotes_defensivos,...,tocos,faltas_cometidas,índice_de_tocos_por_faltas_cometidas,total_de_erros_(soma_de_erros_e_violações),violações,eficiência,assistência,bolas_recuperadas_,duplos_duplos,triplos_duplos
0,McClanahan #22,32,34.50,21.44,6.19,11.06,4.19,3.59,0.69,2.91,...,0.19,2.69,0.07,2.31,0.50,14.50,1.75,1.09,0.00,0.00
1,Antonio #11,38,32.13,17.55,5.68,8.58,3.29,4.84,4.84,3.16,...,0.26,2.71,0.10,2.00,0.34,14.66,1.29,0.84,0.05,0.00
2,Lucas Dias #9,38,31.55,17.29,6.16,8.79,2.34,7.42,7.42,5.63,...,0.53,2.13,0.25,1.87,0.18,19.92,2.42,0.79,0.24,0.03
3,Lucas Mariano #28,44,27.24,17.07,6.61,7.50,2.95,5.50,5.50,4.07,...,0.32,1.91,0.17,1.68,0.14,15.77,1.52,0.82,0.07,0.00
4,Thomas #0,34,32.00,17.00,4.94,8.24,3.82,4.79,4.79,4.26,...,0.38,2.41,0.16,3.82,0.65,15.15,3.88,1.15,0.03,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,Motta #0,3,2.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,1.00,0.33,0.00,-0.33,0.33,0.67,0.00,0.00
250,João Mini #1,3,1.74,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,1.00,0.33,0.33,-0.67,0.00,0.00,0.00,0.00
251,Paschoal #8,4,3.08,0.00,0.00,0.00,0.00,0.50,0.50,0.25,...,0.00,0.00,1.00,0.25,0.25,-0.50,0.00,0.00,0.00,0.00
252,Gusthavo S #6,12,1.37,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.17,0.00,0.00,0.00,-0.50,0.00,0.08,0.00,0.00
253,Thiago #20,13,2.10,0.00,0.00,0.00,0.00,0.23,0.23,0.23,...,0.00,0.08,0.00,0.31,0.08,-0.15,0.00,0.08,0.00,0.00

In [53]:
dados = pd.read_csv("nbb.csv")

In [56]:
dados = pd.read_csv("nbb.csv")
columns = []
names = []
for cl in dados.columns:
    cln = cl.split(".")[0]
    if cln not in columns:
        names.append("_".join(cln.split(" ")).lower())
        columns.append(cl) 

dados = dados[columns]
dados.columns = names
dados = dados.dropna()
dados["total_min"] = dados["jogo"]*dados["min_em_quadra"]
dados

,jogadores,jogo,min_em_quadra,pontos,cesta_de_3_pts,cesta_de_2_pts,lances_livres,rebotes,rebotes_ofensivos,rebotes_defensivos,...,faltas_cometidas,índice_de_tocos_por_faltas_cometidas,total_de_erros_(soma_de_erros_e_violações),violações,eficiência,assistência,bolas_recuperadas_,duplos_duplos,triplos_duplos,total_min
0,McClanahan #22,32,34.50,21.44,6.19,11.06,4.19,3.59,0.69,2.91,...,2.69,0.07,2.31,0.50,14.50,1.75,1.09,0.00,0.00,1104.00
1,Antonio #11,38,32.13,17.55,5.68,8.58,3.29,4.84,4.84,3.16,...,2.71,0.10,2.00,0.34,14.66,1.29,0.84,0.05,0.00,1220.94
2,Lucas Dias #9,38,31.55,17.29,6.16,8.79,2.34,7.42,7.42,5.63,...,2.13,0.25,1.87,0.18,19.92,2.42,0.79,0.24,0.03,1198.90
3,Lucas Mariano #28,44,27.24,17.07,6.61,7.50,2.95,5.50,5.50,4.07,...,1.91,0.17,1.68,0.14,15.77,1.52,0.82,0.07,0.00,1198.56
4,Thomas #0,34,32.00,17.00,4.94,8.24,3.82,4.79,4.79,4.26,...,2.41,0.16,3.82,0.65,15.15,3.88,1.15,0.03,0.00,1088.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,Motta #0,3,2.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,1.00,0.33,0.00,-0.33,0.33,0.67,0.00,0.00,6.18
250,João Mini #1,3,1.74,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,1.00,0.33,0.33,-0.67,0.00,0.00,0.00,0.00,5.22
251,Paschoal #8,4,3.08,0.00,0.00,0.00,0.00,0.50,0.50,0.25,...,0.00,1.00,0.25,0.25,-0.50,0.00,0.00,0.00,0.00,12.32
252,Gusthavo S #6,12,1.37,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.17,0.00,0.00,0.00,-0.50,0.00,0.08,0.00,0.00,16.44
253,Thiago #20,13,2.10,0.00,0.00,0.00,0.00,0.23,0.23,0.23,...,0.08,0.00,0.31,0.08,-0.15,0.00,0.08,0.00,0.00,27.30

In [61]:
dados_sort = dados.sort_values(by="total_min",ascending=False)

,jogo,min_em_quadra,pontos,cesta_de_3_pts,cesta_de_2_pts,lances_livres,rebotes,rebotes_ofensivos,rebotes_defensivos,assistências,...,faltas_cometidas,índice_de_tocos_por_faltas_cometidas,total_de_erros_(soma_de_erros_e_violações),violações,eficiência,assistência,bolas_recuperadas_,duplos_duplos,triplos_duplos,total_min
12,47,31.98,14.47,5.11,5.40,3.96,8.26,8.26,7.23,6.15,...,1.55,0.41,3.06,0.13,21.06,6.15,0.98,0.32,0.04,1503.06
17,47,30.13,13.81,3.70,7.57,2.53,4.02,4.02,3.21,3.15,...,1.87,0.05,1.06,0.15,16.36,3.15,0.94,0.00,0.00,1416.11
100,43,30.17,8.07,4.81,2.79,0.47,4.14,4.14,3.58,7.19,...,2.28,0.03,2.42,0.14,13.65,7.19,1.65,0.14,0.02,1297.31
18,44,29.00,13.59,1.36,9.77,2.45,2.66,2.66,1.84,2.82,...,2.27,0.01,1.36,0.20,14.23,2.82,1.07,0.00,0.00,1276.00
54,38,33.28,10.55,5.92,2.26,2.37,2.82,2.82,2.45,7.13,...,1.29,0.02,1.76,0.11,14.32,7.13,0.92,0.13,0.00,1264.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,27,5.39,2.04,0.00,1.63,0.41,1.59,1.59,1.00,0.07,...,1.15,0.32,0.37,0.04,3.15,0.07,0.07,0.00,0.00,145.53
207,17,7.76,1.18,0.00,1.06,0.12,1.29,1.29,1.06,0.06,...,1.59,0.15,0.41,0.12,1.71,0.06,0.24,0.00,0.00,131.92
221,18,6.19,0.67,0.00,0.44,0.22,1.33,1.33,1.06,0.28,...,1.44,0.04,0.67,0.11,1.72,0.28,0.17,0.00,0.00,111.42
163,11,9.65,2.91,1.09,1.45,0.36,1.27,1.27,1.09,0.55,...,0.82,0.11,0.64,0.18,2.45,0.55,0.27,0.00,0.00,106.15
177,15,7.05,2.07,0.80,0.93,0.33,0.53,0.53,0.33,0.40,...,1.47,0.00,0.47,0.33,1.53,0.40,0.40,0.00,0.00,105.75

In [38]:
dados.to_csv("nbb2.csv")

In [69]:
dados_sort = dados_sort[dados_sort["total_min"]>=100]
escala = MinMaxScaler()
X = escala.fit_transform(dados_sort.drop("jogadores",axis=1))

In [70]:
agrupamento = KMeans(n_clusters=5,n_init=10)
dados_agrupados = agrupamento.fit_predict(X)

In [72]:
pd.DataFrame({'jogadores':dados_sort["jogadores"],'grupo':dados_agrupados})

             jogadores  grupo
12       Georginho #14      3
17   David Jackson #32      4
100          Elinho #5      4
18          Bennett #3      4
54            Ruivo #4      4
..                 ...    ...
178         Felipe #22      1
207   Vitor Borges #28      2
221           Dida #22      2
163         Shamell #8      2
177          Elias #27      2

[184 rows x 2 columns]